name: ZipRelease
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    name: Zip Folder
    steps:
    - uses: actions/checkout@master

    - name: Install Composer dependencies
      run: composer install
      working-directory: skeleton

    - name: Zip
      run: zip -r release.zip .
      working-directory: skeleton